server:
  port: 8081
  servlet:
    session:
      timeout: 1800

spring:
  application:
    name: rbac
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 47.100.78.245
    #端口号
    port: 6379
    #数据库
    database: 0
    #密码
    password: password
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

    #rabbit配置
  rabbitmq:
    #用户名
    username: admin
    #密码
    password: admin
    #host: 106.14.95.224
    host: 47.100.78.245
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true


mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名(默认是类名)
  type-aliases-package: com.example.rbac.server.pojo
  configuration:
    #打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #自动驼峰命名
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    root: info
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs

jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: yeb-secret
  #JWT的超限期时间(60*60*24)
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: Bearer