server:
  #端口
  port: 8082
spring:
  mail:
    #邮件服务器地址
    host: smtp.qq.com
    #协议
    #protocol: smtp
    #编码格式
    #default-encoding: utf-8
    #授权码
    password: rvtmmgeeczeqddcb
    #发送者邮箱地址
    username: 3212174398@qq.com

  #rabbit配置
  rabbitmq:
    username: admin
    password: admin
    #host: 106.14.95.224
    host: 47.100.78.245
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual


  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 47.100.78.245
    #端口号
    port: 6379
    #数据库
    database: 0
    #密码
    password: password
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  application:
    name: rbac-mail
logging:
  level:
    root: info
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs